version: '3'
services:
  groovy:
    build:
      context: .
    volumes:
      - ./:/home/circleci/java_test/
    environment:
      - CLASSPATH=.:/home/circleci/java_test/libs/*:/home/circleci/java_test/
    working_dir: /home/circleci/java_test/
    tty: true
    command: /bin/bash